name: Add Reviewers on Pull Request

on:
  pull_request:
    branches: [main]
    # types: [opened, ready_for_review, reopened]
    
jobs: 
  add-reviewers:
    name: Add Pull Request Reviewers
    runs-on: windows-latest
    steps:
      - name: Check PR Author
        if: github.event.pull_request.user.login == 'lizzcondrey'
        run:          
            # echo 'found matching user'
            github.event.pull_request.requested_reviewers: ['lizzcondrey'] 