name: Update PR in Project
on:
  pull_request:
    types: 
      - opened

jobs:        
  project-pr-ready:
    name: Update Project Item PR to In Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update project fields
        uses: EndBug/project-fields@v2.0.2
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_url: https://github.com/orgs/experiment-playground/projects/1
          resource_url: https://github.com/my-user/repo/pull/${{ github.event.pull_request.number }}
          values: In Review
          
